export const FETCHED_SEARCHED_WEATHER = "FETCHED_SEARCHED_WEATHER";
export const FETCHED_LOCAL_WEATHER = "FETCHED_LOCAL_WEATHER";
export const LOCAL_IS_LOADING = "LOCAL_IS_LOADING";
export const SEARCH_IS_LOADING = "SEARCH_IS_LOADING";
export const SERVER_ERROR = "SERVER_ERROR";
